/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppRegistroPontosRouteImport } from './routes/app.registro-pontos'
import { Route as AppProdutosRouteImport } from './routes/app.produtos'
import { Route as AppPagamentosRecebidosRouteImport } from './routes/app.pagamentos-recebidos'
import { Route as AppObrasRouteImport } from './routes/app.obras'
import { Route as AppMinhasHorasRouteImport } from './routes/app.minhas-horas'
import { Route as AppMinhaContaRouteImport } from './routes/app.minha-conta'
import { Route as AppMeusPagamentosRouteImport } from './routes/app.meus-pagamentos'
import { Route as AppFuncionariosRouteImport } from './routes/app.funcionarios'
import { Route as AppFolhaRouteImport } from './routes/app.folha'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppDespesasRouteImport } from './routes/app.despesas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppObrasIndexRouteImport } from './routes/app.obras.index'
import { Route as AppObrasIdRouteImport } from './routes/app.obras.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistroPontosRoute = AppRegistroPontosRouteImport.update({
  id: '/registro-pontos',
  path: '/registro-pontos',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRecebidosRoute = AppPagamentosRecebidosRouteImport.update({
  id: '/pagamentos-recebidos',
  path: '/pagamentos-recebidos',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhasHorasRoute = AppMinhasHorasRouteImport.update({
  id: '/minhas-horas',
  path: '/minhas-horas',
  getParentRoute: () => AppRoute,
} as any)
const AppMinhaContaRoute = AppMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AppRoute,
} as any)
const AppMeusPagamentosRoute = AppMeusPagamentosRouteImport.update({
  id: '/meus-pagamentos',
  path: '/meus-pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionariosRoute = AppFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => AppRoute,
} as any)
const AppFolhaRoute = AppFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDespesasRoute = AppDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasIndexRoute = AppObrasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppObrasRoute,
} as any)
const AppObrasIdRoute = AppObrasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppObrasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha': typeof AppFolhaRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/meus-pagamentos': typeof AppMeusPagamentosRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/minhas-horas': typeof AppMinhasHorasRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/app/pagamentos-recebidos': typeof AppPagamentosRecebidosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro-pontos': typeof AppRegistroPontosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/obras/$id': typeof AppObrasIdRoute
  '/app/obras/': typeof AppObrasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha': typeof AppFolhaRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/meus-pagamentos': typeof AppMeusPagamentosRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/minhas-horas': typeof AppMinhasHorasRoute
  '/app/pagamentos-recebidos': typeof AppPagamentosRecebidosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro-pontos': typeof AppRegistroPontosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/obras/$id': typeof AppObrasIdRoute
  '/app/obras': typeof AppObrasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/despesas': typeof AppDespesasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/folha': typeof AppFolhaRoute
  '/app/funcionarios': typeof AppFuncionariosRoute
  '/app/meus-pagamentos': typeof AppMeusPagamentosRoute
  '/app/minha-conta': typeof AppMinhaContaRoute
  '/app/minhas-horas': typeof AppMinhasHorasRoute
  '/app/obras': typeof AppObrasRouteWithChildren
  '/app/pagamentos-recebidos': typeof AppPagamentosRecebidosRoute
  '/app/produtos': typeof AppProdutosRoute
  '/app/registro-pontos': typeof AppRegistroPontosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/obras/$id': typeof AppObrasIdRoute
  '/app/obras/': typeof AppObrasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/despesas'
    | '/app/financeiro'
    | '/app/folha'
    | '/app/funcionarios'
    | '/app/meus-pagamentos'
    | '/app/minha-conta'
    | '/app/minhas-horas'
    | '/app/obras'
    | '/app/pagamentos-recebidos'
    | '/app/produtos'
    | '/app/registro-pontos'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/'
    | '/app/obras/$id'
    | '/app/obras/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/despesas'
    | '/app/financeiro'
    | '/app/folha'
    | '/app/funcionarios'
    | '/app/meus-pagamentos'
    | '/app/minha-conta'
    | '/app/minhas-horas'
    | '/app/pagamentos-recebidos'
    | '/app/produtos'
    | '/app/registro-pontos'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app'
    | '/app/obras/$id'
    | '/app/obras'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/despesas'
    | '/app/financeiro'
    | '/app/folha'
    | '/app/funcionarios'
    | '/app/meus-pagamentos'
    | '/app/minha-conta'
    | '/app/minhas-horas'
    | '/app/obras'
    | '/app/pagamentos-recebidos'
    | '/app/produtos'
    | '/app/registro-pontos'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/app/'
    | '/app/obras/$id'
    | '/app/obras/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/registro-pontos': {
      id: '/app/registro-pontos'
      path: '/registro-pontos'
      fullPath: '/app/registro-pontos'
      preLoaderRoute: typeof AppRegistroPontosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos': {
      id: '/app/produtos'
      path: '/produtos'
      fullPath: '/app/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos-recebidos': {
      id: '/app/pagamentos-recebidos'
      path: '/pagamentos-recebidos'
      fullPath: '/app/pagamentos-recebidos'
      preLoaderRoute: typeof AppPagamentosRecebidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/obras': {
      id: '/app/obras'
      path: '/obras'
      fullPath: '/app/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minhas-horas': {
      id: '/app/minhas-horas'
      path: '/minhas-horas'
      fullPath: '/app/minhas-horas'
      preLoaderRoute: typeof AppMinhasHorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/minha-conta': {
      id: '/app/minha-conta'
      path: '/minha-conta'
      fullPath: '/app/minha-conta'
      preLoaderRoute: typeof AppMinhaContaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meus-pagamentos': {
      id: '/app/meus-pagamentos'
      path: '/meus-pagamentos'
      fullPath: '/app/meus-pagamentos'
      preLoaderRoute: typeof AppMeusPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funcionarios': {
      id: '/app/funcionarios'
      path: '/funcionarios'
      fullPath: '/app/funcionarios'
      preLoaderRoute: typeof AppFuncionariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/folha': {
      id: '/app/folha'
      path: '/folha'
      fullPath: '/app/folha'
      preLoaderRoute: typeof AppFolhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/despesas': {
      id: '/app/despesas'
      path: '/despesas'
      fullPath: '/app/despesas'
      preLoaderRoute: typeof AppDespesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/obras/': {
      id: '/app/obras/'
      path: '/'
      fullPath: '/app/obras/'
      preLoaderRoute: typeof AppObrasIndexRouteImport
      parentRoute: typeof AppObrasRoute
    }
    '/app/obras/$id': {
      id: '/app/obras/$id'
      path: '/$id'
      fullPath: '/app/obras/$id'
      preLoaderRoute: typeof AppObrasIdRouteImport
      parentRoute: typeof AppObrasRoute
    }
  }
}

interface AppObrasRouteChildren {
  AppObrasIdRoute: typeof AppObrasIdRoute
  AppObrasIndexRoute: typeof AppObrasIndexRoute
}

const AppObrasRouteChildren: AppObrasRouteChildren = {
  AppObrasIdRoute: AppObrasIdRoute,
  AppObrasIndexRoute: AppObrasIndexRoute,
}

const AppObrasRouteWithChildren = AppObrasRoute._addFileChildren(
  AppObrasRouteChildren,
)

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDespesasRoute: typeof AppDespesasRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFolhaRoute: typeof AppFolhaRoute
  AppFuncionariosRoute: typeof AppFuncionariosRoute
  AppMeusPagamentosRoute: typeof AppMeusPagamentosRoute
  AppMinhaContaRoute: typeof AppMinhaContaRoute
  AppMinhasHorasRoute: typeof AppMinhasHorasRoute
  AppObrasRoute: typeof AppObrasRouteWithChildren
  AppPagamentosRecebidosRoute: typeof AppPagamentosRecebidosRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRegistroPontosRoute: typeof AppRegistroPontosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDespesasRoute: AppDespesasRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFolhaRoute: AppFolhaRoute,
  AppFuncionariosRoute: AppFuncionariosRoute,
  AppMeusPagamentosRoute: AppMeusPagamentosRoute,
  AppMinhaContaRoute: AppMinhaContaRoute,
  AppMinhasHorasRoute: AppMinhasHorasRoute,
  AppObrasRoute: AppObrasRouteWithChildren,
  AppPagamentosRecebidosRoute: AppPagamentosRecebidosRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRegistroPontosRoute: AppRegistroPontosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
